# Generated by Django 3.0.3 on 2020-02-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to='clients', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profils', verbose_name='Photo de profil'),
        ),
    ]
