# Generated by Django 3.0.3 on 2020-02-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0002_auto_20200212_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='agence',
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='societe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Societe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilite',
            field=models.CharField(choices=[('M', 'M.'), ('F', 'Me'), ('N', 'Mlle')], max_length=1, verbose_name='Profil'),
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Code')),
                ('libelle', models.TextField(blank=True, max_length=30, verbose_name='Libelle')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Agence')),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Poste'),
        ),
    ]
