# Generated by Django 3.0.3 on 2020-02-16 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0003_auto_20200213_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='Date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='client',
            name='Date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='compte',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Client'),
        ),
        migrations.AddField(
            model_name='employe',
            name='Date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employe',
            name='etat',
            field=models.CharField(choices=[('A', 'Actif'), ('I', 'Inactif')], default='', max_length=1, verbose_name='Etat'),
        ),
        migrations.AddField(
            model_name='mantataire',
            name='Date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='poste',
            name='Date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
