# Generated by Django 3.0.3 on 2020-02-16 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0004_auto_20200216_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Code')),
                ('libelle', models.TextField(blank=True, max_length=30, verbose_name='Libelle')),
                ('typecaisse', models.CharField(choices=[('E', 'Entreprise'), ('C', 'Client')], default='', max_length=1, verbose_name='Caisse')),
                ('Date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Agence')),
            ],
        ),
        migrations.AddField(
            model_name='reglement',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Caisse'),
        ),
    ]
