# Generated by Django 3.0.3 on 2020-02-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0006_auto_20200218_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='client',
        ),
    ]
