# Generated by Django 3.0.3 on 2020-02-19 23:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0007_remove_compte_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='caisse',
        ),
        migrations.CreateModel(
            name='CompteCaisse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('A', 'Actif'), ('I', 'Inactif')], max_length=1, verbose_name='Etat')),
                ('Date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Caisse')),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.Compte')),
            ],
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='comptecaisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appbase.CompteCaisse'),
        ),
    ]
